version: '3'

services:
  mysql:
    image: 'mysql:latest'

  redis:
    image: 'redis:latest'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - ./microservices/authenticator:/var/www/html/authenticator
      - ./microservices/email:/var/www/html/email
    depends_on:
      - authenticator
      - email

  authenticator:
    build:
      dockerfile: Dockerfile
      context: ./microservices/authenticator
    volumes:
      - ./microservices/authenticator/:/var/www/html/authenticator

  email:
    build:
      dockerfile: Dockerfile
      context: ./microservices/email
    volumes:
      - ./microservices/email/:/var/www/html/email
