version: '3'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-vlm:/var/lib/mysql:delegated
    networks:
      - foodnet-net

  redis:
    image: 'redis:latest'
    networks:
      - foodnet-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - ./microservices/foodNet-backend:/var/www/html/foodnet
      - ./microservices/authenticator:/var/www/html/authenticator
      - ./microservices/email:/var/www/html/email
      - ./microservices/analytics:/var/www/html/analytics
      - ./microservices/reviews:/var/www/html/reviews
      - ./microservices/sms:/var/www/html/sms
    depends_on:
      - foodnet
      - authenticator
      - email
      - analytics
      - reviews
      - sms
    networks:
      - foodnet-net

  foodnet:
    build:
      dockerfile: Dockerfile
      context: ./microservices/foodNet-backend
    volumes:
      - ./microservices/foodNet-backend/:/var/www/html/foodnet
    networks:
      - foodnet-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  authenticator:
    build:
      dockerfile: Dockerfile
      context: ./microservices/authenticator
    volumes:
      - ./microservices/authenticator/:/var/www/html/authenticator
    networks:
      - foodnet-net

  email:
    build:
      dockerfile: Dockerfile
      context: ./microservices/email
    volumes:
      - ./microservices/email/:/var/www/html/email
    networks:
      - foodnet-net

  analytics:
    build:
      dockerfile: Dockerfile
      context: ./microservices/analytics
    volumes:
      - ./microservices/analytics/:/var/www/html/analytics
    networks:
      - foodnet-net

  reviews:
    build:
      dockerfile: Dockerfile
      context: ./microservices/reviews
    volumes:
      - ./microservices/reviews/:/var/www/html/reviews
    networks:
      - foodnet-net

  sms:
    build:
      dockerfile: Dockerfile
      context: ./microservices/sms
    volumes:
      - ./microservices/sms/:/var/www/html/sms
    networks:
      - foodnet-net

networks:
  foodnet-net:
    driver: bridge

volumes:
  mysql-vlm:
  redis-vlm: